version: '3.2'
services:
  laravel:
    restart: unless-stopped
    depends_on:
      - meilisearch
      - memcached
      - mongodb
      - mailhog
      - mysql
      - redis
      - minio

  mysql:
    restart: unless-stopped

  phpmyadmin:
    restart: unless-stopped
    depends_on:
      - mysql

  mongodb:
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    depends_on:
      - echo-server
      - mailhog
      - laravel

  redis:
    restart: unless-stopped

  mailhog:
    restart: unless-stopped

  echo-server:
    restart: unless-stopped
    depends_on:
      - redis

  node:
    restart: unless-stopped
    depends_on:
      - mongodb
      - mysql
      - redis

  memcached:
    restart: unless-stopped

  minio:
    restart: unless-stopped

  meilisearch:
    restart: unless-stopped

  meilisearch-dashboard:
    restart: unless-stopped
