#!/bin/bash
source ${LARADHOC_BASE_PATH}/.laradhoc

source ${LARADHOC_BASE_PATH}/bin/environment

docker run -it -v ${LARADHOC_BASE_PATH}/${APP_SRC:-.}:/app driebit/node-gulp $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
