#!/bin/bash
source ${LARACKER_BASE_PATH}/.laracker

if [ -f ${LARACKER_BASE_PATH}/bin/.stage ]; then
    source ${LARACKER_BASE_PATH}/bin/.stage
fi

source ${LARACKER_BASE_PATH}/bin/envfiles

if [ "$1" == "--new" ] ; then
    ${LARACKER_BASE_PATH}/.docker/scripts/composer install --ignore-platform-reqs
    ${LARACKER_BASE_PATH}/.docker/scripts/composer dump-autoload
    ${LARACKER_BASE_PATH}/.docker/scripts/artisan --env=server key:generate
fi

${LARACKER_BASE_PATH}/.docker/scripts/artisan config:clear

