#!/bin/bash

STAGE=DEV

if [ "$1" == "--prod" ] || [ "$1" == "--production" ]; then
    STAGE=PROD
fi
if [ "$1" == "--dev" ] || [ "$1" == "--development" ]; then
    STAGE=DEV
fi
if [ "$1" == "--test" ] || [ "$1" == "--testing" ]; then
    STAGE=TEST
fi

echo "STAGE="$STAGE > ${LARACKER_BASE_PATH}/bin/.stage
echo "STAGE MODE: "$STAGE

source ${LARACKER_BASE_PATH}/.laracker
source ${LARACKER_BASE_PATH}/bin/buildenv

KEY_PATH="${LARACKER_BASE_PATH}/.docker/images/nginx/ssl"
ECHO_SSL_PATH="${LARACKER_BASE_PATH}/.docker/images/echo-server/ssl"

if [ $NGINX_ENABLE_HTTPS == 1 ] && ! [ -x "$(command -v openssl)" ]; then
    echo -e "\nError: openssl is not installed." >&2
    echo -e "Please install openssl then try again.\n" >&2
    exit 1
fi

if [ $NGINX_ENABLE_HTTPS == 1 ] ; then
    echo "Creating a new self-signed certificate for domain '${APP_HOST}'..."
    openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
    -subj "/C=CA/ST=QC/O=Company, Inc./CN=${APP_HOST}" \
    -out ${KEY_PATH}/${APP_HOST}.crt \
    -keyout ${KEY_PATH}/${APP_HOST}.key 2>/dev/null
    cp -f ${KEY_PATH}/${APP_HOST}.crt ${ECHO_SSL_PATH}/server.crt
    cp -f ${KEY_PATH}/${APP_HOST}.key ${ECHO_SSL_PATH}/server.key
fi

DOCKER_COMPOSE_LIST=("${LARACKER_BASE_PATH}/docker-compose.yml")
if [ $STAGE == "DEV" ] || [ $STAGE == "TEST" ]; then
    if [ -f "${LARACKER_BASE_PATH}/docker-compose.local.yml" ]; then
        DOCKER_COMPOSE_LIST+=("${LARACKER_BASE_PATH}/docker-compose.local.yml")
    fi
fi
if [ -f "${LARACKER_BASE_PATH}/docker-compose.override.yaml" ]; then
    DOCKER_COMPOSE_LIST+=("${LARACKER_BASE_PATH}/docker-compose.override.yaml")
fi
DOCKER_COMPOSE_FILES=$(IFS="|"; echo "${DOCKER_COMPOSE_LIST[*]}")
DOCKER_COMPOSE_FILES=$(echo "${DOCKER_COMPOSE_FILES}" | sed -e 's/|/ --file /')

source ${LARACKER_BASE_PATH}/bin/envfiles

docker-compose \
--env-file ${LARACKER_BASE_PATH}/bin/.env \
--project-directory ${LARACKER_BASE_PATH} \
--project-name "${CONTAINER_PREFIX}" \
--file $(echo $DOCKER_COMPOSE_FILES) \
up -d --build --no-deps -- $SERVICES_ENABLE
