#!/bin/bash
source ${LARADHOC_BASE_PATH}/.laradhoc

LARADHOC_ENV=${LARADHOC_BASE_PATH}/${APP_SRC}/.laradhoc
INSTALLER_PATH=${LARADHOC_BASE_PATH}/$APP_SRC/.docker/installer

mkdir -p ${LARADHOC_BASE_PATH}/$APP_SRC/tmp

docker-compose --env-file ${LARADHOC_ENV} -f ${INSTALLER_PATH}/docker-compose.yml up

cp -Ra ${LARADHOC_BASE_PATH}/$APP_SRC/tmp/. ${LARADHOC_BASE_PATH}/$APP_SRC
rm -rf ${LARADHOC_BASE_PATH}/$APP_SRC/tmp
${LARADHOC_BASE_PATH}/.docker/scripts/init-laravel --new
rm -rf .git
