#!/bin/bash
source ${LARADHOC_BASE_PATH}/.laradhoc

PATH_SRC="${LARADHOC_BASE_PATH}/${APP_SRC:-.}"

docker-compose \
--env-file ${LARADHOC_BASE_PATH}/bin/.env \
--project-directory ${LARADHOC_BASE_PATH}/.docker/installer \
run -v ${PATH_SRC}:/app -- installer

${LARADHOC_BASE_PATH}/.docker/scripts/init-laravel --new
