#!/bin/bash

source ${LARACKER_BASE_PATH}/.docker/scripts/common/colors

echo -e "\n${ERROR}!!!!!!!!! WARNING !!!!!!!!!${NC}\n"
echo "- all volumes will be REMOVED (you'll loose your MySql data)"
echo "- the ${APP_SRC:-.} folder will be DELETED"
echo "- all containers will be stopped "
echo -e "\nAre your really sure? To confirm, type:   nah\n"

read input
if [ ! "$input" == "nah" ] ; then
    echo -e "\nNobody got hurt :)\n"
    exit 0
fi

source ${LARACKER_BASE_PATH}/.laracker
source ${LARACKER_BASE_PATH}/bin/buildenv

echo "Stopping all containers and removing volumes..."

docker-compose \
--env-file ${LARACKER_BASE_PATH}/bin/.env \
--project-directory ${LARACKER_BASE_PATH} \
--file ${LARACKER_BASE_PATH}/docker-compose.yml \
--file ${LARACKER_BASE_PATH}/docker-compose.override.yml \
down -v

echo "Deleting ${APP_SRC:-.} folder..."
rm -rf ${LARACKER_BASE_PATH}/${APP_SRC:-.}
