#!/bin/bash
source ${LARACKER_BASE_PATH}/.laracker
source ${LARACKER_BASE_PATH}/bin/buildenv

docker-compose \
--env-file ${LARACKER_BASE_PATH}/bin/.env \
--project-directory ${LARACKER_BASE_PATH} \
--project-name "$CONTAINER_PREFIX" \
--file ${LARACKER_BASE_PATH}/docker-compose.yml \
--file ${LARACKER_BASE_PATH}/docker-compose.override.yml \
run node $@
