#!/bin/bash
source ${LARADHOC_BASE_PATH}/.laradhoc

source ${LARADHOC_BASE_PATH}/bin/environment

docker-compose --env-file ${LARADHOC_BASE_PATH}/bin/.env --project-directory ${LARADHOC_BASE_PATH} --project-name "$CONTAINER_PREFIX" run node $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10}
