#!/bin/bash

STAGE=DEV

if [ "$1" == "--prod" ] || [ "$1" == "--production" ]; then
    STAGE=PROD
fi
if [ "$1" == "--dev" ] || [ "$1" == "--development" ]; then
    STAGE=DEV
fi
if [ "$1" == "--test" ] || [ "$1" == "--testing" ]; then
    STAGE=TEST
fi

echo "STAGE="$STAGE > ${LARACKER_BASE_PATH}/bin/.stage

echo "STAGE MODE: "$STAGE

source ${LARACKER_BASE_PATH}/.laracker
source ${LARACKER_BASE_PATH}/bin/buildenv

DOCKER_COMPOSE_LIST=("${LARACKER_BASE_PATH}/docker-compose.yml")
if [ $STAGE == "DEV" ] || [ $STAGE == "TEST" ]; then
    if [ -f "${LARACKER_BASE_PATH}/docker-compose.local.yml" ]; then
        DOCKER_COMPOSE_LIST+=("${LARACKER_BASE_PATH}/docker-compose.local.yml")
    fi
fi
if [ -f "${LARACKER_BASE_PATH}/docker-compose.override.yaml" ]; then
    DOCKER_COMPOSE_LIST+=("${LARACKER_BASE_PATH}/docker-compose.override.yaml")
fi
DOCKER_COMPOSE_FILES=$(IFS="|"; echo "${DOCKER_COMPOSE_LIST[*]}")
DOCKER_COMPOSE_FILES=$(echo "${DOCKER_COMPOSE_FILES}" | sed -e 's/|/ --file /')

source ${LARACKER_BASE_PATH}/bin/envfiles

docker-compose \
--env-file ${LARACKER_BASE_PATH}/bin/.env \
--project-directory ${LARACKER_BASE_PATH} \
--project-name "$CONTAINER_PREFIX" \
--file $(echo $DOCKER_COMPOSE_FILES) \
up -d --no-deps -- $SERVICES_ENABLE
