#!/bin/bash

DEV=false
PROD=false
TEST=false
TESTING=false
PRODUCTION=false
DEVELOPMENT=false

if [ "$1" == "--prod" ] || [ "$1" == "--production" ]; then
    PRODUCTION=true
    PROD=$PRODUCTION
fi
if [ "$1" == "--dev" ] || [ "$1" == "--development" ]; then
    DEVELOPMENT=true
    DEV=$DEVELOPMENT
fi
if [ "$1" == "--test" ] || [ "$1" == "--testing" ]; then
    TESTING=true
    TEST=$TESTING
fi

source ${LARACKER_BASE_PATH}/.laracker
source ${LARACKER_BASE_PATH}/bin/buildenv

docker-compose \
--env-file ${LARACKER_BASE_PATH}/bin/.env \
--project-directory ${LARACKER_BASE_PATH} \
--project-name "$CONTAINER_PREFIX" \
--file ${LARACKER_BASE_PATH}/docker-compose.yml \
--file ${LARACKER_BASE_PATH}/docker-compose.override.yml \
up -d --no-deps $@ -- $SERVICES_ENABLE
